apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ac-backend:latest
          imagePullPolicy: Never        # использовать локальный образ
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: taskmanager-config
          livenessProbe:                # K8s проверяет что сервис живой
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000